stages:
  - test
test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    CONTAINER_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - docker version
    - apk update
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - ./test.sh
