version: 2
jobs:
  unit-tests:
    docker:
      - image: mhart/alpine-node:10.16.0
    steps:
      - checkout
      - run:
          name: Run Jest unit tests
          command: |
            yarn
            yarn test
  integration-test:
    machine: true
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            apk update
            apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
            pip install docker-compose
      - run:
          name: Create Dependent Docker Network
          command: |
            docker network create nginx-proxy
      - run: ./test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - unit-tests
      - integration-test
